# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)

apiVersion: kaptain.org/1.7
kind: spec-check-filter-release
metadata:
  description: "KaptainPM schema - JSON Schema for KaptainPM.yaml project manifests"

spec:

  global:
    release:
      versioning:
        maxParts: '2'

  main:
    quality:
      branches:
        blockSlashes: true
      commits:
        blockConventional: true
    specBuild:
      type: schema
      packagingBaseImage: scratch

    docker:
      platform: linux/amd64,linux/arm64

    hooks:
      postVersionsAndNaming: .github/bin/generate-kind-schemas.bash
      postDockerTests: .github/bin/verify-schemas-on-examples.bash

  platform:
    githubActions:
      release:
        verbatimFiles: 'src/examples/project-full.yaml,src/examples/project-min.yaml,src/examples/final-full.yaml,src/examples/final-min.yaml,src/examples/layer-source-full.yaml,src/examples/layer-source-min.yaml,src/examples/layer-full.yaml,src/examples/layer-min.yaml,src/examples/layerset-source-full.yaml,src/examples/layerset-source-min.yaml,src/examples/layerset-full.yaml,src/examples/layerset-min.yaml'
