# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Both job-mode post-deploy sleeps set, with deployMode job.

apiVersion: kaptain.org/1.2
kind: kubernetes-run-environment
spec:
  main:
    environment:
      deployMode: job
      jobPostDeploySleepAfterSuccess: 0s
      jobPostDeploySleepAfterFailure: 2d
