# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# A probe-level terminationGracePeriodSeconds is allowed on liveness and
# startup probes.

apiVersion: kaptain.org/1.2
kind: kubernetes-app-manifests-only
spec:
  main:
    generators:
      workload:
        probes:
          liveness:
            terminationGracePeriodSeconds: "30"
          startup:
            terminationGracePeriodSeconds: "60"
