# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Generation of the env's image pull Secrets can be switched off.

apiVersion: kaptain.org/1.2
kind: kubernetes-run-environment
spec:
  main:
    environment:
      autoGenerateImagePullSecrets: false
