# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Provider names resolve to a plugin filename and are lower case only.

apiVersion: kaptain.org/1.2
kind: kubernetes-app-docker-dockerfile
spec:
  contents:
    - "Docker|bundle-foo:1.0"
