# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Registry namespace must reject a leading slash.

apiVersion: kaptain.org/1.2
kind: kubernetes-app-docker-dockerfile
spec:
  main:
    docker:
      targetNamespace: /kube-kaptain
