# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# A Namespace name is used exactly as given, so there is no nameSuffix.

apiVersion: kaptain.org/1.2
kind: kubernetes-app-manifests-only
spec:
  main:
    generators:
      namespace:
        enabled: true
        name: shared-tools
        nameSuffix: '-blue'
