# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Compound durations are not supported: one integer and one unit.

apiVersion: kaptain.org/1.2
kind: kubernetes-run-environment
spec:
  main:
    environment:
      deployMode: job
      jobPostDeploySleepAfterSuccess: 1h30m
