# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# Only run builds may carry an environment block.

apiVersion: kaptain.org/1.2
kind: basic-quality-and-versioning
spec:
  main:
    environment:
      deployMode: deployment
