# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# imagePullSecrets only drives generation, so it may not be set when the
# user supplies their own deploy manifests.

apiVersion: kaptain.org/1.2
kind: kubernetes-run-environment
spec:
  main:
    environment:
      generateIdealEnvironmentDeployManifests: false
      imagePullSecrets: DISABLED
