# SPDX-License-Identifier: CC0-1.0
# This file is released to the public domain. Use freely without attribution.
#
# Builds, validates, and releases the KaptainPM JSON Schema.

name: Spec Check Filter Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/spec-check-filter-release.yaml@1.0.86
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      spec-type: 'schema'
      tag-version-max-parts: 2
      hook-post-versions-and-naming-script-sub-path: bin/generate-kind-schemas.bash
      hook-post-docker-tests-script-sub-path: bin/verify-schemas-on-examples.bash
      github-release-verbatim-files: 'src/examples/project-full.yaml,src/examples/layer-full.yaml,src/examples/layerset-full.yaml'
